### ISSUE TITLE
interface_target add link library produce CMake error

### ISSUE THREAD

**Issue by Scicomath** [bloomberg/bde-tools#36] opened 2021-06-29 03:52 UTC
I am trying to add a library to a package following the instructions in [here](https://bloomberg.github.io/bde-tools/cmake/customization.html#how-to-extend-package-processing).

However, after I add a library defined in my CMake, CMake produces an error that says:
`CMake Error: install(EXPORT "hblInterfaceTargets" ...) includes target "hblr-PRIVATE" which requires target "XXX" that is not in any export set.`
The XXX above is the library I am trying to add.

How can I fix this error?

**Comment by osubboo** [comment] 2021-07-07 01:51
Can you share the full code snippets? Or, rather create a library skeleton with no code payload ( a single component with fake functionality) and share it on GitHub. It is hard to isolate the cause of this error without having full code and repo layout. Likely there are some missing dependencies.

**Comment by Scicomath** [comment] 2021-07-07 13:37
> Can you share the full code snippets? Or, rather create a library skeleton with no code payload ( a single component with fake functionality) and share it on GitHub. It is hard to isolate the cause of this error without having full code and repo layout. Likely there are some missing dependencies.

I create a demo here: https://github.com/Scicomath/bde_demo

**Comment by osubboo** [comment] 2021-07-08 12:06
Will have a access to a computer tomorrow(for testing), but hbl.dep file missing my_add dependency ( single line "my_add").

**Comment by osubboo** [comment] 2021-07-09 16:33
I've created a PR that illustrates the addition of the library:
https://github.com/Scicomath/bde_demo/pull/1

Note that I had to guess the initial intention of this sample code. my guess if that you have "non structured" library that you want to build as part of the repo and link to one of your components.

**Comment by osubboo** [comment] 2021-08-18 14:42
Closing the issue as we do not receive any feedback from the requester.

**Closed by osubboo** 2021-08-18 14:42 UTC
